services:
  auth:
    build:
      context: ../auth
      dockerfile: ../auth/Dockerfile
    container_name: auth
    ports:
      - "8081:80"
    volumes:
      - ./auth:/app
    depends_on:
      - database
    env_file:
      - ../auth/.env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/breizhsport_auth_db"


  product:
    build:
      context: ../product
      dockerfile: ../product/Dockerfile
    container_name: product
    ports:
      - "8082:80"
    volumes:
      - ./product:/app
    depends_on:
      - database
    env_file:
      - ../product/.env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/breizhsport_product_db"

  database:
    image: postgres:15.9-bullseye
    container_name: shared_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: breizhsport_shared_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
