kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dc2
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8000
        hostPort: 8002
        protocol: TCP
      - containerPort: 8001
        hostPort: 8003
        protocol: TCP
