kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dc-5-nodes
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8000
        hostPort: 8000
        protocol: TCP
      - containerPort: 8001
        hostPort: 8001
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
  - role: worker